project:
  type: website
  output-dir: docs 

website:
  title: "CSE 111 Final Project Fun and Cool"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: REPORT.qmd
        text: REPORT
      - href: showcase.qmd
        text: main function showcase 
  page-footer: 
    border: true
    left: "Corey Silver 2026©"
format:
  html:
    toc: true
    # number-sections: true
    # number-depth: 3
    code-fold: true
    code-summary: "Reveal Secrets"
    theme: default   # This strips out the default
    css: styles.css  
